//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASPMVCEntity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student_Info
    {
        public int SrNo { get; set; }
        public string studentName { get; set; }
        public Nullable<System.DateTime> dob { get; set; }
        public string gender { get; set; }
        public string degreeId { get; set; }
        public string branchId { get; set; }
        public string emailId { get; set; }
        public string mobileNo { get; set; }
        public bool iActive { get; set; }
    }
}
